name: CI for Calculator

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run basic syntax check
      run: |
        python -m py_compile calc_operations.py
        python -m py_compile calc_utils.py
        python -m py_compile main.py
        python -m py_compile history.py
        echo "Все файлы компилируются без ошибок"
        
    - name: Test calculator operations
      run: |
        python -c "
from calc_operations import add, subtract, multiply, divide, power, modulo

# Тестируем основные операции
assert add(2, 3) == 5, 'Сложение работает неправильно'
assert subtract(5, 3) == 2, 'Вычитание работает неправильно'  
assert multiply(2, 3) == 6, 'Умножение работает неправильно'
assert divide(6, 3) == 2, 'Деление работает неправильно'
assert power(2, 3) == 8, 'Возведение в степень работает неправильно'
assert modulo(7, 3) == 1, 'Операция modulo работает неправильно'

print('Все математические операции работают корректно')
        "
